app = "edzhulaj-translator"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
